[tool.ruff]
line-length = 100
target-version = "py310"
extend-exclude = ["outputs", "logs", ".streamlit", ".venv", "venv", "__pycache__"]

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "W",   # warning
  "B",   # flake8-bugbear (버그 가능성)
  "I",   # isort (임포트 정리)
  "UP",  # pyupgrade (현대화)
  "SIM", # flake8-simplify (단순화)
]
ignore = [
  "E203",  # slicing 공백(포맷터 충돌 방지)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true          # streamlit, moviepy 등 타입 미제공 라이브러리 무시
check_untyped_defs = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true

# 검사할 파일만 지정
files = [
  "services",
  "utils", 
  "app/app_streamlit.py",
]

# 검사 제외(레거시/실험용)
exclude = "(app/app_streamlit_(old|new|backup)\\.py)$"
